### ISSUE TITLE
Table Headline and colspan?

### ISSUE THREAD

**Issue by muuvmuuv** [tecfu/tty-table#13] opened 2017-01-21 10:15 UTC
Could be cool to add a headline like in a html fieldset the legend and also to add colspan if I want to have one table col across two.

**Comment by tecfu** [comment] 2017-05-27 08:33
Duplicate of #1

**Comment by tecfu** [comment] 2017-05-27 08:33
Feel free to send me a pull request on this if you like.

**Closed by tecfu** 2017-05-27 08:33 UTC
Labels: enhancement
